// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm_NkYNYlTgouxqR6DJGqtO7kkgBGCdSc',
    appId: '1:610539528245:web:cd0e135732fdda5738917c',
    messagingSenderId: '610539528245',
    projectId: 'bmi-calculator-d0dfe',
    authDomain: 'bmi-calculator-d0dfe.firebaseapp.com',
    storageBucket: 'bmi-calculator-d0dfe.appspot.com',
    measurementId: 'G-RLRMZYYVPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeTfNp_FojGiyRxUW2UY7CvMcpmLaNP9w',
    appId: '1:610539528245:android:32838af75229757438917c',
    messagingSenderId: '610539528245',
    projectId: 'bmi-calculator-d0dfe',
    storageBucket: 'bmi-calculator-d0dfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmbg9tn8J7p4HFQp9kcS5EGsGZhNDnZVk',
    appId: '1:610539528245:ios:64e4ebbd4baf497c38917c',
    messagingSenderId: '610539528245',
    projectId: 'bmi-calculator-d0dfe',
    storageBucket: 'bmi-calculator-d0dfe.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmbg9tn8J7p4HFQp9kcS5EGsGZhNDnZVk',
    appId: '1:610539528245:ios:64e4ebbd4baf497c38917c',
    messagingSenderId: '610539528245',
    projectId: 'bmi-calculator-d0dfe',
    storageBucket: 'bmi-calculator-d0dfe.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm_NkYNYlTgouxqR6DJGqtO7kkgBGCdSc',
    appId: '1:610539528245:web:6374c94dad74e7db38917c',
    messagingSenderId: '610539528245',
    projectId: 'bmi-calculator-d0dfe',
    authDomain: 'bmi-calculator-d0dfe.firebaseapp.com',
    storageBucket: 'bmi-calculator-d0dfe.appspot.com',
    measurementId: 'G-CEY9YPB3G1',
  );
}
